---

- name: Install apt dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - lsb-release
      - curl
      - gpg
    state: present

- name: Adding docker's apt repository signing Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker's repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present
    update_cache: true
    filename: docker

- name: Install docker packages
  apt:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Set docker cgroup driver to systemd
  copy:
    src: ../files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
  notify: restart_docker
