---

- name: Install apt dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
    state: present

- name: Adding docker's apt repository signing Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker's repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present
    update_cache: true
    filename: docker

- name: Install docker packages
  apt:
    name:
      - docker-ce
    state: present
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure kubelet is running
  service:
    name: kubelet
    state: started
    enabled: true

